### ISSUE TITLE
BaggerSchemaDoesNotExistForKeyError should specify which key is missing

### ISSUE THREAD

**Issue by Timberbain** [digitalroute/bagger#18]
When getting the error `BaggerSchemaDoesNotExistForKeyError` there is no description of what key is missing. This would be a great addition as it will improve debugging.

```
    Unhandled error. Exiting process. Error
        at new BaggerSchemaDoesNotExistForKeyError (/app/node_modules/@digitalroute/bagger/dist/bagger.umd.js:188:44)
        at SchemaStorage.getRequestSchema (/app/node_modules/@digitalroute/bagger/dist/bagger.umd.js:257:21)
        at Object.getRequestSchema (/app/node_modules/@digitalroute/bagger/dist/bagger.umd.js:2666:28)
        at Object.<anonymous> (/app/src/server/routes/events/metainformation.js:29:55)
        at Module._compile (internal/modules/cjs/loader.js:778:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
```

**Comment by juliuscc** [comment]
The error is thrown here: https://github.com/digitalroute/bagger/blob/66b2e84479602f0979826d80a0d1225224496273/lib/schema_storage.ts#L78-L89

and is declared here: https://github.com/digitalroute/bagger/blob/66b2e84479602f0979826d80a0d1225224496273/lib/schema_storage.ts#L4

I suggest the error-class is created with an error message. Something like
```typescript
throw new BaggerSchemaDoesNotExistForKeyError(`Key: ${key} does not exist.`);
```

**Comment by juliuscc** [comment]
By doing a search in the project I see that there are many places where Errors are handled the same way. The error gets a descriptive name, but there is no nicely formated error message. Maybe this is a larger problem. What do you think @tgun89?
